[package]
name = "racket-wellformed"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "debug"
path = "src/debug.rs"
test = false
bench = false

[dependencies]
pest = "2.0"
pest_derive = "2.0"
web-sys = "0.3.59"
yew = "0.19"
wasm-bindgen = "0.2"
js-sys = "0.3.59"
